### ISSUE TITLE
Could we use SvelteKit instead?

### ISSUE THREAD

**Issue by algoflows** [krmanik/Office-Addin-TaskPane-Svelte#2]
Hey there, can we swap out svelte for SvelteKit and use the static export, or even serve a SvelteKit app from the web?

**Comment by krmanik** [comment]
It may be possible, I will test then post comment here.

**Comment by algoflows** [comment]
Overjoyed you created this mate, about to use this for a project at work!

**Comment by algoflows** [comment]
We could also add tailwind, would be interesting, what are your thoughts?

**Comment by krmanik** [comment]
We can use tailwind also, the build process need to update.
